version: '3'
services:
  workflow-engine:
    container_name: workflow_container
    build: .
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./workflow_engine:/app
    ports:
      - "8000:8000"
    env_file:
      - ./workflow_engine/.env
    image: workflow_image
    depends_on:
      - db
      - redis

  celery-worker:
    container_name: celery_worker_container
    build: .
    command: celery -A workflow_engine worker -l info
    volumes:
      - ./workflow_engine:/app
    environment:
      CELERY_BROKER_URL: $CELERY_BROKER_URL
      CELERY_RESULT_BACKEND: $CELERY_RESULT_BACKEND
    depends_on:
      - db
      - redis

  db:
    container_name: postgres
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: $POSTGRESQL_NAME
      POSTGRES_USER: $POSTGRESQL_USER
      POSTGRES_PASSWORD: $POSTGRESQL_PWD
    ports:
      - "5432:5432"

  redis:
    container_name: redis
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  redis_data:
